/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Controller.CtrlEleve;
import Controller.CtrlCategorie;
import Controller.CtrlVehicule;
import Controller.CtrlMoniteur;
import Controller.CtrlStats;
import Controller.CtrlLecon;
import Entities.Categorie;
import Entities.Moniteur;
import Entities.Vehicule;
import Tools.ModelJTable;
import java.text.SimpleDateFormat;



/**
 *
 * @author amout
 */
public class FrmAdmin extends javax.swing.JFrame {

    
    
    
    static Categorie laCategorie;
    CtrlEleve ctrlEleve;
    CtrlLecon ctrlLecon;
    CtrlMoniteur ctrlMoniteur;
    CtrlCategorie ctrlCategorie;
    CtrlVehicule ctrlVehicule;
    CtrlStats ctrlStats;    
    ModelJTable mdlVehicule;
    ModelJTable mdlCategorie;
    ModelJTable mdlMoniteur;
    ModelJTable mdlPlanningMoniteur;
    ModelJTable mdlPlanning;
    ModelJTable mdlPlanningEleve;
    ModelJTable mdlEleve;
    
    

        
    /**
     * Creates new form FrmAdmin
     */
    public FrmAdmin() {
        initComponents();
        ctrlEleve = new CtrlEleve();
        ctrlLecon = new CtrlLecon();
        ctrlCategorie = new CtrlCategorie();
        ctrlMoniteur = new CtrlMoniteur();
        ctrlVehicule = new CtrlVehicule();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jtpOnglets = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        lblPrenom = new javax.swing.JLabel();
        lblSexe = new javax.swing.JLabel();
        lblVille = new javax.swing.JLabel();
        lblAdresse = new javax.swing.JLabel();
        txtMarque = new javax.swing.JTextField();
        txtModele = new javax.swing.JTextField();
        txtImmatriculation = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVehicule = new javax.swing.JTable();
        btnValiderVehicule = new javax.swing.JButton();
        cboCategorie = new javax.swing.JComboBox<>();
        lblError = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblNom1 = new javax.swing.JLabel();
        lblPrenom1 = new javax.swing.JLabel();
        txtLibelle = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCategorie = new javax.swing.JTable();
        btnValiderCategorie = new javax.swing.JButton();
        sldPrix = new javax.swing.JSlider();
        txtPrix = new javax.swing.JTextField();
        lblPrenom3 = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        txtIDMono = new javax.swing.JLabel();
        lblNom2 = new javax.swing.JLabel();
        lblPrenom2 = new javax.swing.JLabel();
        lblSexe1 = new javax.swing.JLabel();
        lblVille1 = new javax.swing.JLabel();
        lblAdresse1 = new javax.swing.JLabel();
        txtPrenomMoniteur = new javax.swing.JTextField();
        txtNomMoniteur = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblMoniteur = new javax.swing.JTable();
        btnValiderMoniteur = new javax.swing.JButton();
        txtAdresse2 = new javax.swing.JTextField();
        txtPostalMoniteur = new javax.swing.JTextField();
        lblVille2 = new javax.swing.JLabel();
        txtVille = new javax.swing.JTextField();
        lblVille3 = new javax.swing.JLabel();
        lblVille4 = new javax.swing.JLabel();
        txtTelephoneMoniteur = new javax.swing.JTextField();
        cboSexe = new javax.swing.JComboBox<>();
        lblPrenom4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlanningLecon = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblPlanningMoniteur = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblMoniteurs = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblPlanningEleve = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblEleve = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        btnAfficherStats = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jtpOnglets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtpOngletsMouseClicked(evt);
            }
        });

        jPanel7.setBackground(java.awt.SystemColor.activeCaption);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("Ajouter/Modifier un véhicule");

        lblNom.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblNom.setText("Marque : ");

        lblPrenom.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblPrenom.setText("Immatriculation : ");

        lblSexe.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblSexe.setText("Modèle :");

        lblVille.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblVille.setText("Catégorie :");

        lblAdresse.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblAdresse.setText("Année : ");

        txtMarque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarqueActionPerformed(evt);
            }
        });

        txtImmatriculation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImmatriculationActionPerformed(evt);
            }
        });

        tblVehicule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblVehicule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVehiculeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblVehicule);

        btnValiderVehicule.setText("Valider");
        btnValiderVehicule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnValiderVehiculeMouseClicked(evt);
            }
        });
        btnValiderVehicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderVehiculeActionPerformed(evt);
            }
        });

        lblError.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(101, 101, 101)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSexe, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblNom, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblVille, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtImmatriculation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                        .addComponent(txtMarque, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                        .addComponent(txtModele, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(btnValiderVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(96, 96, 96)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(lblPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(912, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(txtImmatriculation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNom)
                            .addComponent(txtMarque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSexe)
                            .addComponent(txtModele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblAdresse)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblVille)
                            .addComponent(cboCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnValiderVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(170, 170, 170)
                    .addComponent(lblPrenom)
                    .addContainerGap(370, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtpOnglets.addTab("Véhicule", jPanel2);

        jPanel8.setBackground(java.awt.SystemColor.activeCaption);

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel4.setText("Ajouter/Modifer une catégorie");

        lblNom1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblNom1.setText("Prix : ");

        lblPrenom1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblPrenom1.setText("Libellé : ");

        txtLibelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLibelleActionPerformed(evt);
            }
        });

        tblCategorie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCategorie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategorieMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblCategorie);

        btnValiderCategorie.setText("Valider");
        btnValiderCategorie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnValiderCategorieMouseClicked(evt);
            }
        });
        btnValiderCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderCategorieActionPerformed(evt);
            }
        });

        sldPrix.setDoubleBuffered(true);
        sldPrix.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldPrixStateChanged(evt);
            }
        });

        txtPrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrixActionPerformed(evt);
            }
        });

        lblPrenom3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblPrenom3.setText("ID : ");

        txtID.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNom1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrenom3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrenom1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sldPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(txtLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(btnValiderCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrenom3)
                            .addComponent(txtID))
                        .addGap(90, 90, 90)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPrenom1)
                                    .addComponent(txtLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblNom1)
                                    .addComponent(sldPrix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(58, 58, 58)
                .addComponent(btnValiderCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jtpOnglets.addTab("Catégorie", jPanel3);

        jPanel10.setBackground(java.awt.SystemColor.activeCaption);

        txtIDMono.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N

        lblNom2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblNom2.setText("Prénom : ");

        lblPrenom2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblPrenom2.setText("Nom : ");

        lblSexe1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblSexe1.setText("Sexe : ");

        lblVille1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblVille1.setText("Adresse : ");

        lblAdresse1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblAdresse1.setText("Date de naissance : ");

        txtPrenomMoniteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrenomMoniteurActionPerformed(evt);
            }
        });

        txtNomMoniteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomMoniteurActionPerformed(evt);
            }
        });

        tblMoniteur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMoniteur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMoniteurMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblMoniteur);

        btnValiderMoniteur.setText("Valider");
        btnValiderMoniteur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnValiderMoniteurMouseClicked(evt);
            }
        });
        btnValiderMoniteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderMoniteurActionPerformed(evt);
            }
        });

        txtAdresse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdresse2ActionPerformed(evt);
            }
        });

        lblVille2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblVille2.setText("Code postal : ");

        lblVille3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblVille3.setText("Téléphone :");

        lblVille4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblVille4.setText("Ville :");

        cboSexe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homme", "Femme", "Non-binaire" }));

        lblPrenom4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblPrenom4.setText("ID : ");

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel7.setText("Ajouter/Modifier un moniteur");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVille3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPrenom2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblNom2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblSexe1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPrenomMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cboSexe, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNomMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIDMono, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblVille4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblVille2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblVille1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblAdresse1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAdresse2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtVille, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                                .addComponent(txtPostalMoniteur)
                                                .addComponent(txtTelephoneMoniteur, javax.swing.GroupLayout.Alignment.TRAILING)))))
                                .addGap(22, 22, 22))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(lblPrenom4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(btnValiderMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(677, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPrenom4)
                                    .addComponent(txtIDMono))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNomMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPrenom2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNom2)
                                    .addComponent(txtPrenomMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSexe1))
                                .addGap(18, 18, 18)
                                .addComponent(lblAdresse1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblVille1)
                                    .addComponent(txtAdresse2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblVille2)
                                    .addComponent(txtPostalMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVille4)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVille3)
                            .addComponent(txtTelephoneMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnValiderMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(481, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jtpOnglets.addTab("Moniteurs", jPanel4);

        jTabbedPane1.setBackground(new java.awt.Color(153, 204, 255));

        jPanel13.setBackground(java.awt.SystemColor.activeCaption);

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel3.setText("Planning des leçons à venir");

        tblPlanningLecon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Heure", "Moniteur", "Payé ?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPlanningLecon);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(548, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Leçons", jPanel13);

        jPanel14.setBackground(java.awt.SystemColor.activeCaption);

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel5.setText("Plannings par moniteur");

        tblPlanningMoniteur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Heure", "Moniteur", "Payé ?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblPlanningMoniteur);

        tblMoniteurs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMoniteurs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMoniteursMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblMoniteurs);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Par moniteur", jPanel14);

        jPanel15.setBackground(java.awt.SystemColor.activeCaption);

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel6.setText("Planning par élève");

        tblPlanningEleve.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Heure", "Moniteur", "Payé ?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblPlanningEleve);

        tblEleve.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEleve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEleveMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblEleve);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(392, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Par élève", jPanel15);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jtpOnglets.addTab("Plannings", jPanel5);

        jPanel12.setBackground(java.awt.SystemColor.activeCaption);

        btnAfficherStats.setText("Valider");
        btnAfficherStats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAfficherStatsMouseClicked(evt);
            }
        });
        btnAfficherStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfficherStatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(btnAfficherStats, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(880, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(btnAfficherStats, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        jtpOnglets.addTab("Statistiques", jPanel12);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1165, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jtpOnglets, javax.swing.GroupLayout.PREFERRED_SIZE, 1165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jtpOnglets))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMarqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarqueActionPerformed

    private void txtImmatriculationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImmatriculationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImmatriculationActionPerformed
    
    
    private void jtpOngletsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtpOngletsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtpOngletsMouseClicked

    private void btnValiderVehiculeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValiderVehiculeMouseClicked
        // TODO add your handling code here:
        if (jcalAnnee.getYear() == 0 || txtMarque.getText().length() == 0 || txtImmatriculation.getText().length() == 0 || txtModele.getText().length() == 0)
        {
            lblError.setText("Veuillez saisir toutes les informations");
        }
        else
        {
            int annee = jcalAnnee.getYear();
            String imma = txtImmatriculation.getText();
            String marque = txtMarque.getText();
            String modele = txtModele.getText();
            int codeCat = ctrlCategorie.getCodeCatByLib(cboCategorie.getSelectedItem().toString());
            if(tblVehicule.getSelectedRow() == -1)
            {
                ctrlVehicule.addVehicule(imma, annee, modele, marque, codeCat);
            }
            else
            {
                String matricule =  (String)tblVehicule.getValueAt(tblVehicule.getSelectedRow(), 0);
                ctrlVehicule.modifierVehicule(matricule, annee, modele, marque, codeCat);
            }

            mdlVehicule = new ModelJTable();
            mdlVehicule.loadDatasVehicule(ctrlVehicule.getAllVehicule());
            tblVehicule.setModel(mdlVehicule);
        }
        
        
    }//GEN-LAST:event_btnValiderVehiculeMouseClicked

    private void btnValiderVehiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderVehiculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnValiderVehiculeActionPerformed

    private void btnValiderCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderCategorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnValiderCategorieActionPerformed

    private void btnValiderCategorieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValiderCategorieMouseClicked
        // TODO add your handling code here:
        
        String lib = txtLibelle.getText();
        int prix = sldPrix.getValue();
        int codeCat = 0;
        
        if(txtID.getText() == "")
        {
            codeCat = ctrlCategorie.getLastIDCategorie() + 1;
            ctrlCategorie.addCategorie(  lib, codeCat, prix);
        }
        else
        {
            codeCat = Integer.parseInt(txtID.getText());
            ctrlCategorie.modifierCategorie(lib, codeCat, prix);
        }
        mdlCategorie = new ModelJTable();       
        mdlCategorie.loadDatasCategorie(ctrlCategorie.getAllCategorie());
        tblCategorie.setModel(mdlCategorie);
        
        
        txtID.setText("");
        
        
        
        
        
    }//GEN-LAST:event_btnValiderCategorieMouseClicked

    private void txtLibelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLibelleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibelleActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        mdlCategorie = new ModelJTable();
        mdlEleve = new ModelJTable();
        mdlMoniteur = new ModelJTable();
        mdlPlanning = new ModelJTable();
        mdlVehicule = new ModelJTable();
           
        
        
        mdlCategorie.loadDatasCategorie(ctrlCategorie.getAllCategorie());
        tblCategorie.setModel(mdlCategorie);
        
        mdlEleve.loadDatasEleve(ctrlEleve.getAllEleve());
        tblEleve.setModel(mdlEleve);
        
        mdlMoniteur.loadDatasMoniteur(ctrlMoniteur.getAllMoniteur());
        tblMoniteur.setModel(mdlMoniteur);
        tblMoniteurs.setModel(mdlMoniteur);
        
        mdlVehicule.loadDatasVehicule(ctrlVehicule.getAllVehicule());
        tblVehicule.setModel(mdlVehicule);
        
        mdlPlanning.loadDatasPlanningAdmin(ctrlLecon.getAllLecon());
        tblPlanningLecon.setModel(mdlPlanning);
        
        for(Categorie cat : ctrlCategorie.getAllCategorie())
        {
            cboCategorie.addItem(cat.getLibelle());
        }
        
        String s=Integer.toString(sldPrix.getValue());
        txtPrix.setText(s);
        
        
                
        
        
        
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void tblVehiculeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVehiculeMouseClicked
        // TODO add your handling code here:
        Vehicule vehicule = null;

        String matricule =  (String)tblVehicule.getValueAt(tblVehicule.getSelectedRow(), 0);
                
        vehicule = new Vehicule(ctrlVehicule.getVehiculeByImmatriculation(matricule).getImmatriculation(), ctrlVehicule.getVehiculeByImmatriculation(matricule).getAnnee(), ctrlVehicule.getVehiculeByImmatriculation(matricule).getCodeCategorie(), ctrlVehicule.getVehiculeByImmatriculation(matricule).getModele(), ctrlVehicule.getVehiculeByImmatriculation(matricule).getMarque());
        
        jcalAnnee.setYear(vehicule.getAnnee());
        txtImmatriculation.setText(vehicule.getImmatriculation());
        txtModele.setText(vehicule.getModele());
        txtMarque.setText(vehicule.getMarque());
        cboCategorie.setSelectedItem(ctrlCategorie.getLibByCodeCat(vehicule.getCodeCategorie()));
    }//GEN-LAST:event_tblVehiculeMouseClicked

    private void tblCategorieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategorieMouseClicked
        // TODO add your handling code here:
        Categorie cat = null;
        int codeCat = (Integer)tblCategorie.getValueAt(tblCategorie.getSelectedRow(), 0);
        
        System.out.println(codeCat);
        cat = new Categorie(codeCat, ctrlCategorie.getCategorieByCodeCat(codeCat).getLibelle(), ctrlCategorie.getCategorieByCodeCat(codeCat).getPrix());
        String p=Integer.toString(cat.getCodeCategorie());
        txtID.setText(p);
        txtLibelle.setText(cat.getLibelle());
        sldPrix.setValue(cat.getPrix());
        
        
        
    }//GEN-LAST:event_tblCategorieMouseClicked

    private void txtPrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrixActionPerformed

    private void sldPrixStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldPrixStateChanged
        // TODO add your handling code here:
        String s=Integer.toString(sldPrix.getValue());
        txtPrix.setText(s);




        
    }//GEN-LAST:event_sldPrixStateChanged

    private void txtAdresse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdresse2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdresse2ActionPerformed

    private void btnValiderMoniteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderMoniteurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnValiderMoniteurActionPerformed

    private void btnValiderMoniteurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValiderMoniteurMouseClicked
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dateNaiss = sdf.format(jcalDateNaiss.getDate());
        String prenom = txtPrenomMoniteur.getText();
        String nom = txtNomMoniteur.getText();
        String adresse = txtAdresse2.getText();
        String ville = txtVille.getText();
        String codePostal = txtPostalMoniteur.getText();
        String telephone = txtTelephoneMoniteur.getText();
        String libSexe = cboSexe.getSelectedItem().toString();
        int sexe = 0;
        if(libSexe == "Homme"){
            sexe = 1;
        }
        if(libSexe == "Femme"){
            sexe = 2;
        }
        if(libSexe == "Non binaire"){
            sexe = 3;
        }

        if(txtIDMono.getText() == "")
        {
            ctrlMoniteur.addMoniteur(ctrlMoniteur.getLastIDMoniteur()+1, nom, prenom, sexe, adresse, telephone, codePostal, ville, dateNaiss);
        }
        else
        {
            int id = Integer.parseInt(txtIDMono.getText());
            System.out.println(id);
            ctrlMoniteur.modifierUnMoniteur(id, nom, prenom, adresse, telephone, sexe, codePostal, ville, dateNaiss);
        }

        mdlMoniteur = new ModelJTable();
        mdlMoniteur.loadDatasMoniteur(ctrlMoniteur.getAllMoniteur());
        tblMoniteur.setModel(mdlMoniteur);
        
        txtIDMono.setText("");
        txtAdresse2.setText("");
        txtNomMoniteur.setText("");
        txtPostalMoniteur.setText("");
        txtPrenomMoniteur.setText("");
        txtTelephoneMoniteur.setText("");
        txtVille.setText("");
        
        

    }//GEN-LAST:event_btnValiderMoniteurMouseClicked

    private void tblMoniteurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMoniteurMouseClicked
        // TODO add your handling code here:

        Moniteur mono = null;

        int codeMono =  (Integer)tblMoniteur.getValueAt(tblMoniteur.getSelectedRow(), 0);
        System.out.println(codeMono);
        mono = ctrlMoniteur.getMoniteurByCodeMono(codeMono);

        jcalDateNaiss.setDate(mono.getDateDeNaissance());
        txtNomMoniteur.setText(mono.getNom());
        txtPostalMoniteur.setText(mono.getCodePostal());
        txtTelephoneMoniteur.setText(mono.getTelephone());
        txtPrenomMoniteur.setText(mono.getPrenom());
        txtVille.setText(mono.getVille());
        txtAdresse2.setText(mono.getAdresse());

        String cm =Integer.toString(mono.getCodeMoniteur());
        txtIDMono.setText(cm);

    }//GEN-LAST:event_tblMoniteurMouseClicked

    private void txtNomMoniteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomMoniteurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomMoniteurActionPerformed

    private void txtPrenomMoniteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrenomMoniteurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrenomMoniteurActionPerformed

    private void tblMoniteursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMoniteursMouseClicked
        // TODO add your handling code here:
        
        int codeMonoSelected = 0;
        mdlPlanningMoniteur = new ModelJTable();
        
        
        codeMonoSelected =  (Integer)tblMoniteur.getValueAt(tblMoniteurs.getSelectedRow(), 0);
        mdlPlanningMoniteur.loadDatasPlanningMoniteur(ctrlLecon.getAllLeconByCodeMoniteur(codeMonoSelected));
        tblPlanningMoniteur.setModel(mdlPlanningMoniteur);
    }//GEN-LAST:event_tblMoniteursMouseClicked

    private void tblEleveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEleveMouseClicked
        // TODO add your handling code here:
        
        int codeEleveSelected = 0;

        mdlPlanningEleve = new ModelJTable();
        
        codeEleveSelected =  (Integer)tblEleve.getValueAt(tblEleve.getSelectedRow(), 0);
        mdlPlanningEleve.loadDatasPlanningEleve(ctrlLecon.getAllLeconByCodeEleve(codeEleveSelected));
        tblPlanningEleve.setModel(mdlPlanningEleve);
    }//GEN-LAST:event_tblEleveMouseClicked

    private void btnAfficherStatsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAfficherStatsMouseClicked
        // TODO add your handling code here:
        
        ctrlStats  = new CtrlStats("Statistiques", "Rapport leçons reglées/non-réglées", ctrlLecon.getCA(), ctrlLecon.getNonReglee());
        ctrlStats.pack();
        ctrlStats.setVisible(true);
        
        
    }//GEN-LAST:event_btnAfficherStatsMouseClicked

    private void btnAfficherStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfficherStatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAfficherStatsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfficherStats;
    private javax.swing.JButton btnValiderCategorie;
    private javax.swing.JButton btnValiderMoniteur;
    private javax.swing.JButton btnValiderVehicule;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cboCategorie;
    private javax.swing.JComboBox<String> cboSexe;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jtpOnglets;
    private javax.swing.JLabel lblAdresse;
    private javax.swing.JLabel lblAdresse1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblNom1;
    private javax.swing.JLabel lblNom2;
    private javax.swing.JLabel lblPrenom;
    private javax.swing.JLabel lblPrenom1;
    private javax.swing.JLabel lblPrenom2;
    private javax.swing.JLabel lblPrenom3;
    private javax.swing.JLabel lblPrenom4;
    private javax.swing.JLabel lblSexe;
    private javax.swing.JLabel lblSexe1;
    private javax.swing.JLabel lblVille;
    private javax.swing.JLabel lblVille1;
    private javax.swing.JLabel lblVille2;
    private javax.swing.JLabel lblVille3;
    private javax.swing.JLabel lblVille4;
    private javax.swing.JSlider sldPrix;
    private javax.swing.JTable tblCategorie;
    private javax.swing.JTable tblEleve;
    private javax.swing.JTable tblMoniteur;
    private javax.swing.JTable tblMoniteurs;
    private javax.swing.JTable tblPlanningEleve;
    private javax.swing.JTable tblPlanningLecon;
    private javax.swing.JTable tblPlanningMoniteur;
    private javax.swing.JTable tblVehicule;
    private javax.swing.JTextField txtAdresse2;
    private javax.swing.JLabel txtID;
    private javax.swing.JLabel txtIDMono;
    private javax.swing.JTextField txtImmatriculation;
    private javax.swing.JTextField txtLibelle;
    private javax.swing.JTextField txtMarque;
    private javax.swing.JTextField txtModele;
    private javax.swing.JTextField txtNomMoniteur;
    private javax.swing.JTextField txtPostalMoniteur;
    private javax.swing.JTextField txtPrenomMoniteur;
    private javax.swing.JTextField txtPrix;
    private javax.swing.JTextField txtTelephoneMoniteur;
    private javax.swing.JTextField txtVille;
    // End of variables declaration//GEN-END:variables
}
